config/routes.rb
Rails.application.routes.draw do
  devise_for :admins , controllers: { sessions: 'admins/sessions' , registrations: 'admins/registrations'}
  devise_for :librarians, controllers: { sessions: 'librarians/sessions' , registrations: 'librarians/registrations'}
  devise_for :students, controllers: { sessions: 'students/sessions' , registrations: 'students/registrations'}
  resources :transactions
  resources :librarians
  resources :libraries
  resources :admins
  resources :books
  resources :students
  resources :home_pages

  root 'home_page#index'

  get '/search' => 'books#search', :as => 'search'
  get '/checkout' => 'books#checkout', :as => 'checkout'
  get '/returnBook' => 'books#returnBook', :as => 'returnBook'
  get '/repealRequest' => 'books#repealRequest', :as => 'repealRequest'
  get '/bookmark' => 'books#bookmark', :as => 'bookmark'
  get '/unbookmark' => 'books#unbookmark', :as => 'unbookmark'
  get '/requestBook' => 'books#requestBook', :as => 'requestBook'
  get '/student_libraries_index' => 'libraries#student_libraries_index', :as => 'student_libraries_index'

  get '/restricted' => 'librarians#restricted', :as => 'restricted'
  get '/getBookmarkBooks' => 'books#getBookmarkBooks', :as => 'getBookmarkBooks'
  get '/librarian_book_view' => 'books#librarian_book_view', :as => 'librarian_book_view'
  get '/books_students' => 'books#books_students', :as => 'books_students'
  get '/list_checkedoutBooks' => 'books#list_checkedoutBooks', :as => 'list_checkedoutBooks'
  get '/list_checkedoutBooksAndStudentsAdmin' => 'books#list_checkedoutBooksAndStudentsAdmin', :as => 'list_checkedoutBooksAndStudentsAdmin'
  get '/show_librarians' => 'admins#show_librarians', :as => 'show_librarians'
  get '/show_students' => 'admins#show_students', :as => 'show_students'
  get '/show_books' => 'admins#show_books', :as => 'show_books'
  get '/show_libraries' => 'admins#show_libraries', :as => 'show_libraries'
  get '/add_books' => 'books#new', :as => 'add_books'
  get '/add_students' => 'students#new', :as => 'add_students'
  get '/add_librarians' => 'librarians#new', :as => 'add_librarians'
  get '/getStudentBookFine' => 'books#getStudentBookFine', :as => 'getStudentBookFine'
  get '/getOverdueBooks' => 'books#getOverdueBooks', :as => 'getOverdueBooks'
  get '/viewBookHistory' => 'books#viewBookHistory', :as => 'viewBookHistory'
  get '/viewHoldRequestForLibrarian' => 'books#viewHoldRequestForLibrarian', :as => 'viewHoldRequestForLibrarian'
  get '/viewHoldRequestForAdmin' => 'books#viewHoldRequestForAdmin', :as => 'viewHoldRequestForAdmin'
  get '/librarian_special_book' => 'books#librarian_special_book', :as => 'librarian_special_book'
  get '/reject_special_book' => 'books#reject_special_book', :as => 'reject_special_book'
  get '/approve_special_book' => 'books#approve_special_book', :as => 'approve_special_book'
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates_uniqueness_of :email, confirmation: { case_sensitive: false }
  validates_format_of :email, uniqueness: true, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates :password, confirmation: true, length: { minimum: 8 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :library
  validates :isbn, presence: true
  validates :title, presence: true
  validates :authors, presence: true
  validates :published, presence: true
  validates :edition, presence: true
  validates :language, presence: true
  validates :count, presence: true
  validates_uniqueness_of :isbn, confirmation: { case_sensitive: false }
  has_many :bookmark, dependent: :destroy
  has_many :checkout, dependent: :destroy
  has_many :hold_request, dependent: :destroy
  has_many :special_book, dependent: :destroy
  mount_uploader :cover, CoverUploader
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :student
  belongs_to :book
end

app/models/checkout.rb
class Checkout < ApplicationRecord
  belongs_to :student
  belongs_to :book
end

app/models/hold_request.rb
class HoldRequest < ApplicationRecord
  belongs_to :student
  belongs_to :book
end

app/models/librarian.rb
class Librarian < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :library, presence: true
  validates_uniqueness_of :email, confirmation: { case_sensitive: false }
  validates_format_of :email, uniqueness: true, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates :password, confirmation: true, length: { minimum: 8 }
end

app/models/library.rb
class Library < ApplicationRecord
  validates :name, presence: true
  validates :university, presence: true
  validates :location, presence: true
  validates :borrow_limit, presence: true
  validates_uniqueness_of :name,  confirmation: { case_sensitive: false }
  has_many :book, dependent: :destroy

end

app/models/special_book.rb
class SpecialBook < ApplicationRecord
  belongs_to :student
  belongs_to :book
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :email, presence: true
  validates :education_level, presence: true
  validates :university, presence: true
  validates_uniqueness_of :email, confirmation: { case_sensitive: false }
  validates_format_of :email, uniqueness: true, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates :password, confirmation: true, length: { minimum: 8 }
  has_many :bookmark, dependent: :destroy
  has_many :checkout, dependent: :destroy
  has_many :hold_request, dependent: :destroy
  has_many :special_book, dependent: :destroy
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/models/university.rb
class University < ActiveRecord::Base
    UNIVERSITY_TYPES = ["Dai Hoc Bach Khoa","Dai Hoc Kinh Te Quoc Dan", "Dai Hoc Xay Dung"]
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/librarians_helper.rb
module LibrariansHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/add_books.html.erb
<%= render 'form', book: @book %>

app/views/admins/add_librarians.html.erb
<%= render 'form', librarian: @librarian %>

app/views/admins/add_students.html.erb
<%= render 'form', student: @student %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<strong>Note:</strong> Editing your profile will automatically sign you out. You will have to sign back in.
<br>
<br>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Panel</h1>
Name: <%= current_admin.name %><br>
Email: <%=  current_admin.email %><br>
<br>
<br>
<table>
  <th><strong>Admin Rights</strong></th>

  <tr><td><%= link_to 'Edit Profile', edit_admin_path(current_admin) %></td></tr>
  <tr><td></td><tr>
  <tr><td></td><tr>
  <tr><td><strong>Librarians</strong></td><tr>
  <tr><td><%= link_to 'Add Librarian', new_librarian_path %></td></tr>
  <tr><td><%= link_to 'View Librarians (Details/Edit/Delete/Approve)', show_librarians_path %></td></tr>
  <tr><td></td><tr>
  <tr><td></td><tr>
  <tr><td><strong>Libraries</strong></td><tr>
  <tr><td><%= link_to 'Add Library', new_library_path %></tr>
  <tr><td><%= link_to 'View Libraries (Details/Edit/Delete)', show_libraries_path %></td></tr>
  <tr><td></td><tr>
  <tr><td></td><tr>
  <tr><td><strong>Students</strong></td><tr>
  <tr><td><%= link_to 'Add Student', new_student_path %></td></tr>
  <tr><td><%= link_to 'View Students (Details/Edit)', show_students_path %></td></tr>  
  <tr><td><%= link_to 'List of Students who have Checked Out Books', list_checkedoutBooksAndStudentsAdmin_path %></td></tr>  
  <tr><td></td><tr>
  <tr><td></td><tr>
  <tr><td><strong>Books</strong></td><tr>
  <tr><td><%= link_to 'Add Book', add_books_path %></td></tr>
  <tr><td><%= link_to 'View Books (Details/Borrowing History/Edit/Delete)', show_books_path %></tr>
  <tr><td><%= link_to 'View Checked Out Books', list_checkedoutBooks_path %></tr>  
  
    
</table>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/admins/show_books.html.erb
<h1>Books</h1>

<%= form_tag(search_path, :method => "get" , :required => true) do %>  
  
  <%= radio_button_tag(:search_by,"title",:checked => true,) %>Title
  <%= radio_button_tag(:search_by, "authors")%>Author
  <%= radio_button_tag(:search_by, "published")%>Published Date
  <%= radio_button_tag(:search_by, "category")%>Category</p>
    <%= search_field_tag :search, params[:search], placeholder: "Search" , :required => true %>  
      <%= button_tag do%> 
	  <%= t('Search')%>
	  <% end %>

<% end %>
<table border='1'>
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Title</th>
      <th>Authors</th>
      <th>Language</th>
      <th>Subject</th>
      <th>Library</th>
      <th>Available Count</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= book.title %></td>
        <td><%= book.authors %></td>
        <td><%= book.language %></td>
        <td><%= book.subject %></td>
        <td><%=  Library.find(book.library_id ).name %></td>
        <td><%= book.count %></td>
        <% if current_admin.nil? %>          
          <td><%= link_to 'Checkout', controller: "books", action: "checkout", id: book %></td>
          <td><%= link_to 'Bookmark', controller: "books", action: "bookmark", id: book %></td>
          <td><%= link_to 'Request Book', controller: "books", action: "requestBook", id: book %></td>
        <% else %>
          <td><%= link_to 'Show', book %></td>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'View Book History', controller: "books", action: "viewBookHistory", id: book %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/show_librarians.html.erb
<h1>Librarians</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Library</th>
      <th>Approved</th>
      <th>Action</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @librarians.each do |librarian| %>
      <tr>
        <td><%= librarian.name %></td>
        <td><%= librarian.email %></td>
        <td><%= librarian.library %></td>
        <td><%= librarian.approved %></td>
        <td>
        <%= link_to 'Show', librarian %>
        <%= link_to 'Edit/Approve', edit_librarian_path(librarian) %>
        <%= link_to 'Destroy', librarian, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/admins/show_libraries.html.erb
<h1>Libraries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>University</th>
      <th>Location</th>
      <th>Borrow limit</th>
      <th>Overdue fines</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.name %></td>
        <td><%= library.university %></td>
        <td><%= library.location %></td>
        <td><%= library.borrow_limit %></td>
        <td><%= library.overdue_fines %></td>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

app/views/admins/show_students.html.erb
<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
		    <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryManagementSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if student_signed_in?%>
    <%= link_to "Logout", destroy_student_session_path, method: :delete%>
    <%= link_to 'Back', students_path %>
    <% end %>
    <% if librarian_signed_in?%>
    <%= link_to "Logout", destroy_librarian_session_path, method: :delete%>
    <%= link_to 'Back', librarians_path %>
    <% end %>
    <% if admin_signed_in?%>
    <%= link_to "Logout", destroy_admin_session_path, method: :delete%>
    <%= link_to 'Back', admins_path %>
    <% end %>


    <%= yield %>
  </body>
</html>